version: "3.9"
services:
    nginx:
        container_name: nginx_my_porfolio
        restart: always
        build:
            context: ./
        ports:
            - 80:80
        volumes:
            - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf
# docker compose -p my-porfolio up -d

